version: '3'
services:
    myapp:
        build: .
        container_name: "jwt"
        image: jwt/auth:v1.0.3
        networks:
          - jwt_network
        environment:
            - NODE_ENV=production
            - PORT=3000
        ports:
            - 3000:3000
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        networks:
          - jwt_network
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

networks:
  jwt_network: